#!/bin/bash
# Copyright © 2021 Kris Nóva <kris@nivenly.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, softwar
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#    ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗
#    ████╗  ██║██╔═████╗██║   ██║██╔══██╗
#    ██╔██╗ ██║██║██╔██║██║   ██║███████║
#    ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║
#    ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║
#    ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝
#
#   For more information on Alicefile and the alice project
#            https://github.com/kris-nova/alice
#
REPO="krisnova"
NAME="yamyams"
TAG="latest"
SHA="$(git rev-parse HEAD)"